# Generated by Django 5.0.6 on 2024-05-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_plant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='is_published',
            field=models.BooleanField(choices=0, default=1),
        ),
    ]
