# Generated by Django 5.0.6 on 2024-06-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_category_plant_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.category'),
        ),
    ]
