# Generated by Django 5.0.6 on 2024-06-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_plant_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='plants.category'),
        ),
    ]
