# Generated by Django 5.0.6 on 2024-06-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_alter_plant_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='plants.tagpost'),
        ),
    ]
